//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Nql.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="INqlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class NqlBaseListener : INqlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuery([NotNull] NqlParser.QueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuery([NotNull] NqlParser.QueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.playerQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlayerQuery([NotNull] NqlParser.PlayerQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.playerQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlayerQuery([NotNull] NqlParser.PlayerQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.teamQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTeamQuery([NotNull] NqlParser.TeamQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.teamQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTeamQuery([NotNull] NqlParser.TeamQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.gameQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGameQuery([NotNull] NqlParser.GameQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.gameQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGameQuery([NotNull] NqlParser.GameQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.compareQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompareQuery([NotNull] NqlParser.CompareQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.compareQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompareQuery([NotNull] NqlParser.CompareQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.compareTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompareTarget([NotNull] NqlParser.CompareTargetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.compareTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompareTarget([NotNull] NqlParser.CompareTargetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.playerList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlayerList([NotNull] NqlParser.PlayerListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.playerList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlayerList([NotNull] NqlParser.PlayerListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.teamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTeamList([NotNull] NqlParser.TeamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.teamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTeamList([NotNull] NqlParser.TeamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.gameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGameList([NotNull] NqlParser.GameListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.gameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGameList([NotNull] NqlParser.GameListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.fieldSelection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldSelection([NotNull] NqlParser.FieldSelectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.fieldSelection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldSelection([NotNull] NqlParser.FieldSelectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.fieldExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldExpr([NotNull] NqlParser.FieldExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.fieldExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldExpr([NotNull] NqlParser.FieldExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] NqlParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] NqlParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.whereClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhereClause([NotNull] NqlParser.WhereClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.whereClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhereClause([NotNull] NqlParser.WhereClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] NqlParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] NqlParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperator([NotNull] NqlParser.OperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperator([NotNull] NqlParser.OperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] NqlParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] NqlParser.ValueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
