//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Nql.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="NqlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface INqlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery([NotNull] NqlParser.QueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery([NotNull] NqlParser.QueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.playerQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlayerQuery([NotNull] NqlParser.PlayerQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.playerQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlayerQuery([NotNull] NqlParser.PlayerQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.whereClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhereClause([NotNull] NqlParser.WhereClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.whereClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhereClause([NotNull] NqlParser.WhereClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] NqlParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] NqlParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperator([NotNull] NqlParser.OperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperator([NotNull] NqlParser.OperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NqlParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] NqlParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NqlParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] NqlParser.ValueContext context);
}
