//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Nql.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="NqlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface INqlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery([NotNull] NqlParser.QueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.playerQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlayerQuery([NotNull] NqlParser.PlayerQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.teamQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTeamQuery([NotNull] NqlParser.TeamQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.gameQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGameQuery([NotNull] NqlParser.GameQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.compareQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareQuery([NotNull] NqlParser.CompareQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.compareTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareTarget([NotNull] NqlParser.CompareTargetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.playerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlayerList([NotNull] NqlParser.PlayerListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.teamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTeamList([NotNull] NqlParser.TeamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.gameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGameList([NotNull] NqlParser.GameListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.fieldSelection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldSelection([NotNull] NqlParser.FieldSelectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.fieldExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldExpr([NotNull] NqlParser.FieldExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] NqlParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.whereClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhereClause([NotNull] NqlParser.WhereClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] NqlParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator([NotNull] NqlParser.OperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NqlParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] NqlParser.ValueContext context);
}
